services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: nestjs-dev
    ports:
      - "3301:3301"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - rabbitmq
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.development